/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bargiralda.views.bar;

import bargiralda.views.MainView;
import bargiralda.controllers.CrearFondo;
import bargiralda.views.OlvidoPasswordView;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro Muñoz Adan
 */
public class BarLoginView extends javax.swing.JFrame {
    private static final String RUTA_FONDO_BAR = "/resources/backgroundModoBar.png";
    
    CrearFondo fondoBar = new CrearFondo(RUTA_FONDO_BAR);
    
    /**
     * Creates new form UsuarioView
     */
    public BarLoginView() {
        //Se asigna el fondo al jFrame antes de iniciar componentes
        this.setContentPane(fondoBar);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        usuarioLabel = new javax.swing.JLabel();
        contrasennaLabel1 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        usuarioTF = new javax.swing.JTextField();
        olvidadoPassLabel = new javax.swing.JLabel();
        BackjLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bar Giralda - Login (Modo Bar)");
        setMaximumSize(new java.awt.Dimension(1124, 1126));
        setMinimumSize(new java.awt.Dimension(1124, 1126));
        setResizable(false);
        setSize(new java.awt.Dimension(1124, 1126));

        jPanel.setLayout(new GridLayout(2, 2, 10, 10));
        jPanel.setBackground(new Color(255, 255, 255, 200));
        jPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));

        usuarioLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(51, 51, 51));
        usuarioLabel.setText("Usuario:");

        contrasennaLabel1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        contrasennaLabel1.setForeground(new java.awt.Color(51, 51, 51));
        contrasennaLabel1.setText("Contraseña:");

        jButtonLogin.setBackground(new java.awt.Color(237, 28, 36));
        jButtonLogin.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Iniciar Sesión");
        jButtonLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogin.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButtonLogin.setMaximumSize(new java.awt.Dimension(230, 40));
        jButtonLogin.setMinimumSize(new java.awt.Dimension(230, 40));
        jButtonLogin.setPreferredSize(new java.awt.Dimension(230, 40));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        usuarioTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        usuarioTF.setForeground(new java.awt.Color(153, 153, 153));
        usuarioTF.setText("Introducir usuario");
        usuarioTF.setMaximumSize(new java.awt.Dimension(80, 24));
        usuarioTF.setMinimumSize(new java.awt.Dimension(80, 24));
        usuarioTF.setPreferredSize(new java.awt.Dimension(160, 32));
        usuarioTF.setSelectionColor(new java.awt.Color(204, 153, 255));
        usuarioTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioTFMouseClicked(evt);
            }
        });
        usuarioTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTFActionPerformed(evt);
            }
        });

        olvidadoPassLabel.setFont(new java.awt.Font("Sitka Text", 3, 15)); // NOI18N
        olvidadoPassLabel.setForeground(new java.awt.Color(102, 102, 255));
        olvidadoPassLabel.setText("He olvidado mi contraseña");
        olvidadoPassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olvidadoPassLabelMouseClicked(evt);
            }
        });

        BackjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BackLogo.png"))); // NOI18N
        BackjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackjLabelMouseClicked(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setMaximumSize(new java.awt.Dimension(80, 24));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(80, 24));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(80, 24));
        jPasswordField1.setSelectionColor(new java.awt.Color(204, 153, 255));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackjLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(usuarioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(231, 231, 231))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(olvidadoPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(contrasennaLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(contrasennaLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(olvidadoPassLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        boolean esValido = true;
        new BarView().setVisible(true);
        this.setVisible(false);
        
        if (usuarioTF.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "No deje ningún campo vacío");
            esValido = false;
            new BarView().setVisible(true);
            this.setVisible(false);
        }
        
        //Controlar en registro que introduce ok dos veces password
        /*if (!contrasennaTF.getText().equals(contrasennaTF2.getText())) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            esValido = false;
        }*/

        if (jPasswordField1.getText().length() < 5) {
            JOptionPane.showMessageDialog(null, "Debe introducir más de 5 carácteres para su contraseña");
            esValido = false;
        }

        /*if (esValido) {
            ConsultasRegistro conSQL = new ConsultasRegistro(UsuarioTF.getText(), contrasennaTF.getText());
        }*/

        // FALTARIA POR CONTROLAR CUANDO EXISTA ESE USUARIO
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void usuarioTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTFActionPerformed

    private void BackjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackjLabelMouseClicked
        new MainView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackjLabelMouseClicked

    //Accion Click Mouse al pulsar JLabel Olvide mi contraseña
    private void olvidadoPassLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olvidadoPassLabelMouseClicked
        this.setVisible(false); //Si no se hace primero permanece abierta
        //Crear nueva vista JDialog Olvido Contraseña
        new OlvidoPasswordView(this, rootPaneCheckingEnabled).setVisible(true); 
    }//GEN-LAST:event_olvidadoPassLabelMouseClicked

    private void usuarioTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTFMouseClicked
        usuarioTF.setText("");
    }//GEN-LAST:event_usuarioTFMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarLoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarLoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackjLabel;
    private javax.swing.JLabel contrasennaLabel1;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel olvidadoPassLabel;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioTF;
    // End of variables declaration//GEN-END:variables
}
