/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bargiralda.views.bar;

import bargiralda.controllers.CrearFondo;
import bargiralda.views.bar.TPVView;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author Alvaro Muñoz Adan
 */
public class BarView extends javax.swing.JFrame {
    
    private static final String RUTA_FONDO_BAR = "/resources/backgroundModoBar.png";
    
    CrearFondo fondoBar = new CrearFondo(RUTA_FONDO_BAR);
    CrearFondo fondoCaja = new CrearFondo(RUTA_FONDO_BAR);
    CrearFondo fondoAdmin = new CrearFondo(RUTA_FONDO_BAR);
    CrearFondo fondoTPV = new CrearFondo(RUTA_FONDO_BAR);
    TPVView TPV = new TPVView(this, true);
    
    //Flag para controlar si la caja esta abierta y puede hacerse uso del TPV
    boolean isCajaAbierta = false;
    /**
     * Creates new form BarView
     */
    public BarView() {
        this.setContentPane(fondoBar);
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCaja = new javax.swing.JDialog();
        jPanelCaja = new javax.swing.JPanel();
        abrirCajaLabel = new javax.swing.JLabel();
        cerrarCajaLabel = new javax.swing.JLabel();
        BackjLabelCaja = new javax.swing.JLabel();
        jDialogAdminUser = new javax.swing.JDialog();
        jPanelAdminUser = new javax.swing.JPanel();
        BackjLabelAdmin = new javax.swing.JLabel();
        jButtonEditPass = new javax.swing.JButton();
        jPanelDatosPersonales = new javax.swing.JPanel();
        nombreJLabel = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        apellidosJLabel = new javax.swing.JLabel();
        apellidosTF = new javax.swing.JTextField();
        emailJLabel = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jPanelPassword = new javax.swing.JPanel();
        actualPassJLabel = new javax.swing.JLabel();
        jPasswordFieldAdminUser1 = new javax.swing.JPasswordField();
        nuevaPassJLabel = new javax.swing.JLabel();
        jPasswordFieldAdminUser2 = new javax.swing.JPasswordField();
        confirmarPassJLabel = new javax.swing.JLabel();
        jPasswordFieldAdminUser3 = new javax.swing.JPasswordField();
        cambiarPassJLabel = new javax.swing.JLabel();
        datosPersonalesJLabel = new javax.swing.JLabel();
        jButtonEditPersonal = new javax.swing.JButton();
        AdminUserTitleJLabel = new javax.swing.JLabel();
        jLabelAceptarDatosPersonales = new javax.swing.JLabel();
        jLabelCancelarDatosPersonales = new javax.swing.JLabel();
        jLabelAceptarPassword = new javax.swing.JLabel();
        jLabelCancelarPassword = new javax.swing.JLabel();
        jPanelBuscarUsuario = new javax.swing.JPanel();
        usuarioTF = new javax.swing.JTextField();
        usuarioJLabel = new javax.swing.JLabel();
        jButtonBuscarUsuario = new javax.swing.JButton();
        datosPersonalesJLabel1 = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        pedidosLabel = new javax.swing.JLabel();
        adminCartaLabel = new javax.swing.JLabel();
        adminUserLabel = new javax.swing.JLabel();
        cajaLabel = new javax.swing.JLabel();
        tpvLabel = new javax.swing.JLabel();
        informesLabel1 = new javax.swing.JLabel();
        BackjLabel = new javax.swing.JLabel();

        jDialogCaja.setContentPane(fondoCaja);
        jDialogCaja.setTitle("Bar Giralda - Abrir/Cerrar Caja");
        jDialogCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialogCaja.setMinimumSize(new java.awt.Dimension(800, 800));
        jDialogCaja.setResizable(false);
        jDialogCaja.setSize(new java.awt.Dimension(800, 800));

        jPanel.setLayout(new GridLayout(2, 2, 10, 10));
        jPanelCaja.setBackground(new Color(255, 255, 255, 128));
        jPanelCaja.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));

        abrirCajaLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        abrirCajaLabel.setForeground(new java.awt.Color(51, 51, 51));
        abrirCajaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AbrirCajaLogo.png"))); // NOI18N
        abrirCajaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirCajaLabelMouseClicked(evt);
            }
        });

        cerrarCajaLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        cerrarCajaLabel.setForeground(new java.awt.Color(51, 51, 51));
        cerrarCajaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CerrarCajaLogo.png"))); // NOI18N
        cerrarCajaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarCajaLabelMouseClicked(evt);
            }
        });

        BackjLabelCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BackLogo.png"))); // NOI18N
        BackjLabelCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackjLabelCajaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCajaLayout = new javax.swing.GroupLayout(jPanelCaja);
        jPanelCaja.setLayout(jPanelCajaLayout);
        jPanelCajaLayout.setHorizontalGroup(
            jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCajaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackjLabelCaja)
                    .addGroup(jPanelCajaLayout.createSequentialGroup()
                        .addComponent(abrirCajaLabel)
                        .addGap(80, 80, 80)
                        .addComponent(cerrarCajaLabel)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelCajaLayout.setVerticalGroup(
            jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCajaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BackjLabelCaja)
                .addGap(35, 35, 35)
                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cerrarCajaLabel)
                    .addComponent(abrirCajaLabel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogCajaLayout = new javax.swing.GroupLayout(jDialogCaja.getContentPane());
        jDialogCaja.getContentPane().setLayout(jDialogCajaLayout);
        jDialogCajaLayout.setHorizontalGroup(
            jDialogCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCajaLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jPanelCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jDialogCajaLayout.setVerticalGroup(
            jDialogCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCajaLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jPanelCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        jDialogAdminUser.setContentPane(fondoAdmin);
        jDialogAdminUser.setTitle("Bar Giralda - Administrar usuario");
        jDialogAdminUser.setMinimumSize(new java.awt.Dimension(1021, 1122));
        jDialogAdminUser.setResizable(false);
        jDialogAdminUser.setSize(new java.awt.Dimension(1021, 1122));

        jPanelAdminUser.setLayout(new GridLayout(2, 2, 10, 10));
        jPanelAdminUser.setBackground(new Color(255, 255, 255, 220));
        jPanelAdminUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));

        BackjLabelAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BackLogo.png"))); // NOI18N
        BackjLabelAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackjLabelAdminMouseClicked(evt);
            }
        });

        jButtonEditPass.setVisible(false);
        jButtonEditPass.setBackground(new java.awt.Color(237, 28, 36));
        jButtonEditPass.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jButtonEditPass.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditPass.setText("Editar");
        jButtonEditPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButtonEditPass.setBorderPainted(false);
        jButtonEditPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditPass.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButtonEditPass.setMaximumSize(new java.awt.Dimension(230, 40));
        jButtonEditPass.setMinimumSize(new java.awt.Dimension(230, 40));
        jButtonEditPass.setPreferredSize(new java.awt.Dimension(230, 40));
        jButtonEditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPassActionPerformed(evt);
            }
        });

        jPanelDatosPersonales.setBackground(new Color(202, 240, 248, 110));
        jPanelDatosPersonales.setVisible(false);
        jPanelDatosPersonales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jPanelDatosPersonales.setPreferredSize(new java.awt.Dimension(718, 230));

        nombreJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nombreJLabel.setForeground(new java.awt.Color(51, 51, 51));
        nombreJLabel.setText("Nombre:");

        nombreTF.setEditable(false);
        nombreTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        nombreTF.setForeground(new java.awt.Color(153, 153, 153));
        nombreTF.setText("Introducir nombre");
        nombreTF.setMaximumSize(new java.awt.Dimension(80, 24));
        nombreTF.setMinimumSize(new java.awt.Dimension(80, 24));
        nombreTF.setPreferredSize(new java.awt.Dimension(160, 32));
        nombreTF.setSelectionColor(new java.awt.Color(204, 153, 255));

        apellidosJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        apellidosJLabel.setForeground(new java.awt.Color(51, 51, 51));
        apellidosJLabel.setText("Apellidos:");

        apellidosTF.setEditable(false);
        apellidosTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        apellidosTF.setForeground(new java.awt.Color(153, 153, 153));
        apellidosTF.setText("Introducir apellidos");
        apellidosTF.setMaximumSize(new java.awt.Dimension(80, 24));
        apellidosTF.setMinimumSize(new java.awt.Dimension(80, 24));
        apellidosTF.setPreferredSize(new java.awt.Dimension(160, 32));
        apellidosTF.setSelectionColor(new java.awt.Color(204, 153, 255));

        emailJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        emailJLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailJLabel.setText("Correo electrónico:");

        emailTF.setEditable(false);
        emailTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        emailTF.setForeground(new java.awt.Color(153, 153, 153));
        emailTF.setText("Introducir email");
        emailTF.setMaximumSize(new java.awt.Dimension(80, 24));
        emailTF.setMinimumSize(new java.awt.Dimension(80, 24));
        emailTF.setPreferredSize(new java.awt.Dimension(160, 32));
        emailTF.setSelectionColor(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanelDatosPersonalesLayout = new javax.swing.GroupLayout(jPanelDatosPersonales);
        jPanelDatosPersonales.setLayout(jPanelDatosPersonalesLayout);
        jPanelDatosPersonalesLayout.setHorizontalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(162, 406, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelDatosPersonalesLayout.setVerticalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apellidosJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPassword.setBackground(new Color(202, 240, 248, 110));
        jPanelPassword.setVisible(false);
        jPanelPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));

        actualPassJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        actualPassJLabel.setForeground(new java.awt.Color(51, 51, 51));
        actualPassJLabel.setText("Contraseña actual:");

        jPasswordFieldAdminUser1.setEditable(false);
        jPasswordFieldAdminUser1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jPasswordFieldAdminUser1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldAdminUser1.setText("jPasswordField1");
        jPasswordFieldAdminUser1.setMaximumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser1.setMinimumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser1.setPreferredSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser1.setSelectionColor(new java.awt.Color(204, 153, 255));

        nuevaPassJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nuevaPassJLabel.setForeground(new java.awt.Color(51, 51, 51));
        nuevaPassJLabel.setText("Nueva contraseña:");

        jPasswordFieldAdminUser2.setEditable(false);
        jPasswordFieldAdminUser2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jPasswordFieldAdminUser2.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldAdminUser2.setText("jPasswordField1");
        jPasswordFieldAdminUser2.setMaximumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser2.setMinimumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser2.setPreferredSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser2.setSelectionColor(new java.awt.Color(204, 153, 255));

        confirmarPassJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        confirmarPassJLabel.setForeground(new java.awt.Color(51, 51, 51));
        confirmarPassJLabel.setText("Confirmar nueva contraseña:");

        jPasswordFieldAdminUser3.setEditable(false);
        jPasswordFieldAdminUser3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jPasswordFieldAdminUser3.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldAdminUser3.setText("jPasswordField1");
        jPasswordFieldAdminUser3.setMaximumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser3.setMinimumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser3.setPreferredSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser3.setSelectionColor(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanelPasswordLayout = new javax.swing.GroupLayout(jPanelPassword);
        jPanelPassword.setLayout(jPanelPasswordLayout);
        jPanelPasswordLayout.setHorizontalGroup(
            jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(actualPassJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(jPasswordFieldAdminUser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelPasswordLayout.createSequentialGroup()
                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nuevaPassJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldAdminUser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldAdminUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmarPassJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelPasswordLayout.setVerticalGroup(
            jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualPassJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldAdminUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaPassJLabel)
                    .addComponent(confirmarPassJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldAdminUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldAdminUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );

        cambiarPassJLabel.setVisible(false);
        cambiarPassJLabel.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        cambiarPassJLabel.setForeground(new java.awt.Color(0, 204, 204));
        cambiarPassJLabel.setText("Cambiar contraseña");

        datosPersonalesJLabel.setVisible(false);
        datosPersonalesJLabel.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        datosPersonalesJLabel.setForeground(new java.awt.Color(0, 204, 204));
        datosPersonalesJLabel.setText("Datos personales");

        jButtonEditPersonal.setVisible(false);
        jButtonEditPersonal.setBackground(new java.awt.Color(237, 28, 36));
        jButtonEditPersonal.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jButtonEditPersonal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditPersonal.setText("Editar");
        jButtonEditPersonal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButtonEditPersonal.setBorderPainted(false);
        jButtonEditPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditPersonal.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButtonEditPersonal.setMaximumSize(new java.awt.Dimension(230, 40));
        jButtonEditPersonal.setMinimumSize(new java.awt.Dimension(230, 40));
        jButtonEditPersonal.setPreferredSize(new java.awt.Dimension(230, 40));
        jButtonEditPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPersonalActionPerformed(evt);
            }
        });

        AdminUserTitleJLabel.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        AdminUserTitleJLabel.setForeground(new java.awt.Color(0, 204, 204));
        AdminUserTitleJLabel.setText("Administrar Usuarios");

        jLabelAceptarDatosPersonales.setVisible(false);
        jLabelAceptarDatosPersonales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirmarBoton.png"))); // NOI18N
        jLabelAceptarDatosPersonales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAceptarDatosPersonalesMouseClicked(evt);
            }
        });

        jLabelCancelarDatosPersonales.setVisible(false);
        jLabelCancelarDatosPersonales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelarBoton.png"))); // NOI18N
        jLabelCancelarDatosPersonales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelarDatosPersonalesMouseClicked(evt);
            }
        });

        jLabelAceptarPassword.setVisible(false);
        jLabelAceptarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirmarBoton.png"))); // NOI18N
        jLabelAceptarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAceptarPasswordMouseClicked(evt);
            }
        });

        jLabelCancelarPassword.setVisible(false);
        jLabelCancelarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelarBoton.png"))); // NOI18N
        jLabelCancelarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelarPasswordMouseClicked(evt);
            }
        });

        jPanelBuscarUsuario.setBackground(new Color(202, 240, 248, 110));
        jPanelBuscarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jPanelBuscarUsuario.setPreferredSize(new java.awt.Dimension(718, 230));

        usuarioTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        usuarioTF.setForeground(new java.awt.Color(153, 153, 153));
        usuarioTF.setText("Introducir correo usuario");
        usuarioTF.setMaximumSize(new java.awt.Dimension(80, 24));
        usuarioTF.setMinimumSize(new java.awt.Dimension(80, 24));
        usuarioTF.setPreferredSize(new java.awt.Dimension(160, 32));
        usuarioTF.setSelectionColor(new java.awt.Color(204, 153, 255));

        usuarioJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        usuarioJLabel.setForeground(new java.awt.Color(51, 51, 51));
        usuarioJLabel.setText("Usuario:");

        jButtonBuscarUsuario.setBackground(new java.awt.Color(237, 28, 36));
        jButtonBuscarUsuario.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jButtonBuscarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarUsuario.setText("Buscar");
        jButtonBuscarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButtonBuscarUsuario.setBorderPainted(false);
        jButtonBuscarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBuscarUsuario.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButtonBuscarUsuario.setMaximumSize(new java.awt.Dimension(230, 40));
        jButtonBuscarUsuario.setMinimumSize(new java.awt.Dimension(230, 40));
        jButtonBuscarUsuario.setPreferredSize(new java.awt.Dimension(230, 40));
        jButtonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarUsuarioLayout = new javax.swing.GroupLayout(jPanelBuscarUsuario);
        jPanelBuscarUsuario.setLayout(jPanelBuscarUsuarioLayout);
        jPanelBuscarUsuarioLayout.setHorizontalGroup(
            jPanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarUsuarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarUsuarioLayout.createSequentialGroup()
                        .addComponent(usuarioJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelBuscarUsuarioLayout.createSequentialGroup()
                        .addComponent(usuarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        jPanelBuscarUsuarioLayout.setVerticalGroup(
            jPanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(usuarioJLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        datosPersonalesJLabel1.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        datosPersonalesJLabel1.setForeground(new java.awt.Color(0, 204, 204));
        datosPersonalesJLabel1.setText("Buscar usuario");

        javax.swing.GroupLayout jPanelAdminUserLayout = new javax.swing.GroupLayout(jPanelAdminUser);
        jPanelAdminUser.setLayout(jPanelAdminUserLayout);
        jPanelAdminUserLayout.setHorizontalGroup(
            jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datosPersonalesJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                        .addComponent(jButtonEditPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelAceptarDatosPersonales)
                        .addGap(25, 25, 25)
                        .addComponent(jLabelCancelarDatosPersonales))
                    .addComponent(datosPersonalesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiarPassJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                        .addComponent(jButtonEditPass, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelAceptarPassword)
                        .addGap(25, 25, 25)
                        .addComponent(jLabelCancelarPassword))
                    .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                        .addComponent(BackjLabelAdmin)
                        .addGap(204, 204, 204)
                        .addComponent(AdminUserTitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanelAdminUserLayout.setVerticalGroup(
            jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackjLabelAdmin)
                    .addComponent(AdminUserTitleJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(datosPersonalesJLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanelBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(datosPersonalesJLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAceptarDatosPersonales)
                        .addComponent(jLabelCancelarDatosPersonales)))
                .addGap(30, 30, 30)
                .addComponent(cambiarPassJLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAceptarPassword)
                        .addComponent(jLabelCancelarPassword)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jDialogAdminUserLayout = new javax.swing.GroupLayout(jDialogAdminUser.getContentPane());
        jDialogAdminUser.getContentPane().setLayout(jDialogAdminUserLayout);
        jDialogAdminUserLayout.setHorizontalGroup(
            jDialogAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAdminUserLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanelAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jDialogAdminUserLayout.setVerticalGroup(
            jDialogAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAdminUserLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jPanelAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bar Giralda - Home (Modo Bar)");
        setMaximumSize(new java.awt.Dimension(1124, 1126));
        setMinimumSize(new java.awt.Dimension(1124, 1126));
        setResizable(false);
        setSize(new java.awt.Dimension(1124, 1126));

        jPanel.setLayout(new GridLayout(2, 2, 10, 10));
        jPanel.setBackground(new Color(255, 255, 255, 200));
        jPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));

        pedidosLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        pedidosLabel.setForeground(new java.awt.Color(51, 51, 51));
        pedidosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PedidosLogo.png"))); // NOI18N
        pedidosLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedidosLabelMouseClicked(evt);
            }
        });

        adminCartaLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        adminCartaLabel.setForeground(new java.awt.Color(51, 51, 51));
        adminCartaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AdminCartaLogo.png"))); // NOI18N
        adminCartaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminCartaLabelMouseClicked(evt);
            }
        });

        adminUserLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        adminUserLabel.setForeground(new java.awt.Color(51, 51, 51));
        adminUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/UsuariosLogo.png"))); // NOI18N
        adminUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminUserLabelMouseClicked(evt);
            }
        });

        cajaLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        cajaLabel.setForeground(new java.awt.Color(51, 51, 51));
        cajaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AbrirCerrarCajaLogo.png"))); // NOI18N
        cajaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cajaLabelMouseClicked(evt);
            }
        });

        tpvLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        tpvLabel.setForeground(new java.awt.Color(51, 51, 51));
        tpvLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/TPVLogo.png"))); // NOI18N
        tpvLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpvLabelMouseClicked(evt);
            }
        });

        informesLabel1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        informesLabel1.setForeground(new java.awt.Color(51, 51, 51));
        informesLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/InformesLogo.png"))); // NOI18N
        informesLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informesLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaLabel)
                    .addComponent(pedidosLabel))
                .addGap(47, 47, 47)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminCartaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpvLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informesLabel1)
                    .addComponent(adminUserLabel))
                .addGap(30, 30, 30))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cajaLabel)
                    .addComponent(tpvLabel)
                    .addComponent(informesLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pedidosLabel)
                    .addComponent(adminCartaLabel)
                    .addComponent(adminUserLabel))
                .addGap(30, 30, 30))
        );

        BackjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BackLogo.png"))); // NOI18N
        BackjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackjLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackjLabel)
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(BackjLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackjLabelMouseClicked
        new BarLoginView().setVisible(true);
        this.setVisible(false);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_BackjLabelMouseClicked

    private void cajaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaLabelMouseClicked
        jDialogCaja.setVisible(true);      
    }//GEN-LAST:event_cajaLabelMouseClicked

    private void BackjLabelCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackjLabelCajaMouseClicked
        //this.setVisible(true);
        jDialogCaja.setVisible(false);
    }//GEN-LAST:event_BackjLabelCajaMouseClicked

    private void abrirCajaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirCajaLabelMouseClicked
        if (isCajaAbierta) {
            JOptionPane.showMessageDialog(null, "La caja ya estaba abierta");
        } else {
            JOptionPane.showMessageDialog(null, "Has abierto la caja.\n¡Puedes comenzar a usar el TPV y a hacer comandas!");
            isCajaAbierta = true;
        }
    }//GEN-LAST:event_abrirCajaLabelMouseClicked

    private void cerrarCajaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarCajaLabelMouseClicked
        if (isCajaAbierta) {
            JOptionPane.showMessageDialog(null, "Has cerrado la caja");
            isCajaAbierta = false;
        } else {
            JOptionPane.showMessageDialog(null, "La caja ya estaba cerrada");
        }
    }//GEN-LAST:event_cerrarCajaLabelMouseClicked

    private void BackjLabelAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackjLabelAdminMouseClicked
        jDialogAdminUser.setVisible(false);
        jDialogAdminUser.setSize(new java.awt.Dimension(1021, 1122));
        ocultarCamposDatosUser();
    }//GEN-LAST:event_BackjLabelAdminMouseClicked

    private void jButtonEditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPassActionPerformed
        jPasswordFieldAdminUser1.setEditable(true);
        jPasswordFieldAdminUser2.setEditable(true);
        jPasswordFieldAdminUser3.setEditable(true);
        jLabelAceptarPassword.setVisible(true);
        jLabelCancelarPassword.setVisible(true);

    }//GEN-LAST:event_jButtonEditPassActionPerformed

    private void jButtonEditPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPersonalActionPerformed
        nombreTF.setEditable(true);
        apellidosTF.setEditable(true);
        emailTF.setEditable(true);
        jLabelAceptarDatosPersonales.setVisible(true);
        jLabelCancelarDatosPersonales.setVisible(true);
    }//GEN-LAST:event_jButtonEditPersonalActionPerformed

    private void jLabelAceptarDatosPersonalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAceptarDatosPersonalesMouseClicked
        jLabelAceptarDatosPersonales.setVisible(false);
        jLabelCancelarDatosPersonales.setVisible(false);
        JOptionPane.showMessageDialog(null, "Cambios realizados con éxito");
    }//GEN-LAST:event_jLabelAceptarDatosPersonalesMouseClicked

    private void jLabelCancelarDatosPersonalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarDatosPersonalesMouseClicked
        jLabelAceptarDatosPersonales.setVisible(false);
        jLabelCancelarDatosPersonales.setVisible(false);
        JOptionPane.showMessageDialog(null, "No se ha realizado ningún cambio");
    }//GEN-LAST:event_jLabelCancelarDatosPersonalesMouseClicked

    private void jLabelAceptarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAceptarPasswordMouseClicked
        jLabelAceptarPassword.setVisible(false);
        jLabelCancelarPassword.setVisible(false);
        JOptionPane.showMessageDialog(null, "Cambios realizados con éxito");
    }//GEN-LAST:event_jLabelAceptarPasswordMouseClicked

    private void jLabelCancelarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarPasswordMouseClicked
        jLabelAceptarPassword.setVisible(false);
        jLabelCancelarPassword.setVisible(false);
        JOptionPane.showMessageDialog(null, "No se ha realizado ningún cambio");
    }//GEN-LAST:event_jLabelCancelarPasswordMouseClicked

    private void adminUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUserLabelMouseClicked
        jDialogAdminUser.setVisible(true);
    }//GEN-LAST:event_adminUserLabelMouseClicked

    private void jButtonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarUsuarioActionPerformed
        mostrarCamposDatosUser();
        jDialogAdminUser.setSize(new java.awt.Dimension(1221, 1222));
    }//GEN-LAST:event_jButtonBuscarUsuarioActionPerformed

    private void tpvLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpvLabelMouseClicked
        if (isCajaAbierta) {
            TPV.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Tienes que abrir la caja antes de comenzar a usar el TPV");
        }
        
    }//GEN-LAST:event_tpvLabelMouseClicked

    private void informesLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informesLabel1MouseClicked
        JOptionPane.showMessageDialog(this, "Funcionabilidad aún no desarrollada. Disculpen las molestías");
    }//GEN-LAST:event_informesLabel1MouseClicked

    private void adminCartaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminCartaLabelMouseClicked
        JOptionPane.showMessageDialog(this, "Funcionabilidad aún no desarrollada. Disculpen las molestías");
    }//GEN-LAST:event_adminCartaLabelMouseClicked

    private void pedidosLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidosLabelMouseClicked
        JOptionPane.showMessageDialog(this, "Funcionabilidad aún no desarrollada. Disculpen las molestías");
    }//GEN-LAST:event_pedidosLabelMouseClicked

    private void ocultarCamposDatosUser() {
        datosPersonalesJLabel.setVisible(false);
        jPanelDatosPersonales.setVisible(false);
        jButtonEditPersonal.setVisible(false);
        cambiarPassJLabel.setVisible(false);
        jPanelPassword.setVisible(false);
        jButtonEditPass.setVisible(false);
        jLabelAceptarPassword.setVisible(false);
        jLabelCancelarPassword.setVisible(false);
        jLabelAceptarDatosPersonales.setVisible(false);
        jLabelCancelarDatosPersonales.setVisible(false);
    }
    
    private void mostrarCamposDatosUser() {
        datosPersonalesJLabel.setVisible(true);
        jPanelDatosPersonales.setVisible(true);
        jButtonEditPersonal.setVisible(true);
        cambiarPassJLabel.setVisible(true);
        jPanelPassword.setVisible(true);
        jButtonEditPass.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminUserTitleJLabel;
    private javax.swing.JLabel BackjLabel;
    private javax.swing.JLabel BackjLabelAdmin;
    private javax.swing.JLabel BackjLabelCaja;
    private javax.swing.JLabel abrirCajaLabel;
    private javax.swing.JLabel actualPassJLabel;
    private javax.swing.JLabel adminCartaLabel;
    private javax.swing.JLabel adminUserLabel;
    private javax.swing.JLabel apellidosJLabel;
    private javax.swing.JTextField apellidosTF;
    private javax.swing.JLabel cajaLabel;
    private javax.swing.JLabel cambiarPassJLabel;
    private javax.swing.JLabel cerrarCajaLabel;
    private javax.swing.JLabel confirmarPassJLabel;
    private javax.swing.JLabel datosPersonalesJLabel;
    private javax.swing.JLabel datosPersonalesJLabel1;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel informesLabel1;
    private javax.swing.JButton jButtonBuscarUsuario;
    private javax.swing.JButton jButtonEditPass;
    private javax.swing.JButton jButtonEditPersonal;
    private javax.swing.JDialog jDialogAdminUser;
    private javax.swing.JDialog jDialogCaja;
    private javax.swing.JLabel jLabelAceptarDatosPersonales;
    private javax.swing.JLabel jLabelAceptarPassword;
    private javax.swing.JLabel jLabelCancelarDatosPersonales;
    private javax.swing.JLabel jLabelCancelarPassword;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelAdminUser;
    private javax.swing.JPanel jPanelBuscarUsuario;
    private javax.swing.JPanel jPanelCaja;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelPassword;
    private javax.swing.JPasswordField jPasswordFieldAdminUser1;
    private javax.swing.JPasswordField jPasswordFieldAdminUser2;
    private javax.swing.JPasswordField jPasswordFieldAdminUser3;
    private javax.swing.JLabel nombreJLabel;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel nuevaPassJLabel;
    private javax.swing.JLabel pedidosLabel;
    private javax.swing.JLabel tpvLabel;
    private javax.swing.JLabel usuarioJLabel;
    private javax.swing.JTextField usuarioTF;
    // End of variables declaration//GEN-END:variables
}
