/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bargiralda.views;

import bargiralda.BarGiralda;
import bargiralda.controllers.CrearFondo;
import java.awt.Color;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.UIManager;

/**
 *
 * @author Alvaro Muñoz Adan
 */
public class LoadingView extends javax.swing.JFrame implements Runnable {
    
    //Ruta imagen de fondo
    private static final String RUTA_FONDO_CARGA = "/resources/GiraldaAnochecer.jpeg";
    
     //Creamos objeto para crear fondos y le asignamos la ruta de la imagen
    CrearFondo fondoCarga = new CrearFondo(RUTA_FONDO_CARGA);
    
    //Contador para crear porcentaje en barra de carga jProgressBar
    int contadorCarga; 
    
    
    /**
     * Creates new form LoadingView
     */
    public LoadingView() {
        //Primero settear fondo antes de iniciar componentes (si no el resto de componentes no se veran)
        this.setContentPane(fondoCarga);
        initComponents();
        this.contadorCarga = 0;
        
        Thread hiloCarga = new Thread(this);
        hiloCarga.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCargaGif = new javax.swing.JLabel();
        jLabelPorcentajeCarga = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabelVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 618));
        setMinimumSize(new java.awt.Dimension(1100, 618));
        setPreferredSize(new java.awt.Dimension(1100, 618));
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 618));

        jLabelCargaGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cargaImagen.gif"))); // NOI18N
        jLabelCargaGif.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jLabelPorcentajeCarga.setBackground(new java.awt.Color(191, 0, 20));
        jLabelPorcentajeCarga.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabelPorcentajeCarga.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPorcentajeCarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPorcentajeCarga.setText("jLabelPorcentajeCarga");

        jProgressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabelVersion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelVersion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVersion.setText("Bar Giralda ©  [Desarrollado por: Álvaro Muñoz Adán]  [Alcalá de Guadaira 2023]  Versión 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabelVersion)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPorcentajeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCargaGif))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelCargaGif)
                .addGap(35, 35, 35)
                .addComponent(jLabelPorcentajeCarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCargaGif;
    private javax.swing.JLabel jLabelPorcentajeCarga;
    private javax.swing.JLabel jLabelVersion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
                try {
            while (contadorCarga <= 100) {
                this.jProgressBar.setValue(contadorCarga);
                this.jLabelPorcentajeCarga.setText("Cargando... "+contadorCarga + "%");
                contadorCarga++;
            
                Thread.sleep(100);
            }
        } catch (InterruptedException e) {
            Logger.getLogger(BarGiralda.class.getName()).log(Level.SEVERE, null, e);
        }
        this.dispose();
        //Una vez acaba la carga se carga el JFrame principal
        new MainView().setVisible(true);
    }
}
