/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bargiralda.views;

import bargiralda.views.usuario.UsuarioLoginView;
import bargiralda.views.bar.BarLoginView;
import bargiralda.controllers.CrearFondo;

/**
 *
 * @author Álvaro Muñoz Adán
 */
public class MainView extends javax.swing.JFrame {

    private static final String RUTA_FONDO_MAIN = "/resources/fondo-barGiralda.png";
    //Se crea un objeto Crear Fondo para cada JFrame al que se le asigna la ruta de la imagen
    CrearFondo fondoMain = new CrearFondo(RUTA_FONDO_MAIN);
    /**
     * Creates new form MainView
     */
    public MainView() {
        //Se asigna el fondo al jFrame Principal (El resto se asignan al pulsar sobre el boton que abre acada JFrame)
        this.setContentPane(fondoMain);        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelModoBar = new javax.swing.JLabel();
        jLabelModoUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bar Giralda - Principal");
        setMaximumSize(new java.awt.Dimension(1125, 1125));
        setMinimumSize(new java.awt.Dimension(1125, 1125));
        setPreferredSize(new java.awt.Dimension(1125, 1125));
        setSize(new java.awt.Dimension(1125, 1125));

        jLabelModoBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LabelModoBar.png"))); // NOI18N
        jLabelModoBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelModoBarMouseClicked(evt);
            }
        });

        jLabelModoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LabelModoUsuario.png"))); // NOI18N
        jLabelModoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelModoUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabelModoBar)
                .addGap(160, 160, 160)
                .addComponent(jLabelModoUsuario)
                .addContainerGap(1176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModoBar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabelModoUsuario)))
                .addGap(172, 172, 172))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelModoBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelModoBarMouseClicked
        new BarLoginView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelModoBarMouseClicked

    private void jLabelModoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelModoUsuarioMouseClicked
        new UsuarioLoginView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelModoUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelModoBar;
    private javax.swing.JLabel jLabelModoUsuario;
    // End of variables declaration//GEN-END:variables
}
