/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package bargiralda.views.usuario;

import bargiralda.views.*;
import bargiralda.controllers.CrearFondo;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro Muñoz Adan
 */
public class FormularioRegistroView extends javax.swing.JDialog {
    
    private static final String RUTA_FONDO_MAIN = "/resources/fondo-barGiralda.png";
    
    //Se crea un objeto Crear Fondo para cada JFrame al que se le asigna la ruta de la imagen
    CrearFondo fondoMain = new CrearFondo(RUTA_FONDO_MAIN);
    /**
     * Creates new form OlvidoPasswordView
     */
    public FormularioRegistroView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setContentPane(fondoMain);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        BackjLabel1 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        emailJLabel = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        apellidosJLabel = new javax.swing.JLabel();
        apellidosTF = new javax.swing.JTextField();
        apellidosJLabel1 = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        apellidosJLabel2 = new javax.swing.JLabel();
        apellidosJLabel3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1025, 1025));
        setMinimumSize(new java.awt.Dimension(1025, 1025));
        setName("forgotPasswordjDialog"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1025, 1025));
        setResizable(false);
        setSize(new java.awt.Dimension(1025, 1025));

        jPanel.setLayout(new GridLayout(2, 2, 10, 10));
        jPanel.setBackground(new Color(255, 255, 255, 200));
        jPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));

        BackjLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BackLogo.png"))); // NOI18N
        BackjLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackjLabel1MouseClicked(evt);
            }
        });

        emailTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        emailTF.setForeground(new java.awt.Color(153, 153, 153));
        emailTF.setText("Introducir email");
        emailTF.setMaximumSize(new java.awt.Dimension(80, 24));
        emailTF.setMinimumSize(new java.awt.Dimension(80, 24));
        emailTF.setPreferredSize(new java.awt.Dimension(160, 32));
        emailTF.setSelectionColor(new java.awt.Color(204, 153, 255));
        emailTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTFMouseClicked(evt);
            }
        });

        emailJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        emailJLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailJLabel.setText("Correo electrónico:");

        jButtonReset.setBackground(new java.awt.Color(237, 28, 36));
        jButtonReset.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReset.setText("Resetear formulario");
        jButtonReset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButtonReset.setBorderPainted(false);
        jButtonReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReset.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButtonReset.setMaximumSize(new java.awt.Dimension(230, 40));
        jButtonReset.setMinimumSize(new java.awt.Dimension(230, 40));
        jButtonReset.setPreferredSize(new java.awt.Dimension(230, 40));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonLogin.setBackground(new java.awt.Color(237, 28, 36));
        jButtonLogin.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Enviar");
        jButtonLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogin.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButtonLogin.setMaximumSize(new java.awt.Dimension(230, 40));
        jButtonLogin.setMinimumSize(new java.awt.Dimension(230, 40));
        jButtonLogin.setPreferredSize(new java.awt.Dimension(230, 40));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        apellidosJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        apellidosJLabel.setForeground(new java.awt.Color(51, 51, 51));
        apellidosJLabel.setText("Apellidos:");

        apellidosTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        apellidosTF.setForeground(new java.awt.Color(153, 153, 153));
        apellidosTF.setText("Introducir apellidos");
        apellidosTF.setMaximumSize(new java.awt.Dimension(80, 24));
        apellidosTF.setMinimumSize(new java.awt.Dimension(80, 24));
        apellidosTF.setPreferredSize(new java.awt.Dimension(160, 32));
        apellidosTF.setSelectionColor(new java.awt.Color(204, 153, 255));
        apellidosTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apellidosTFMouseClicked(evt);
            }
        });

        apellidosJLabel1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        apellidosJLabel1.setForeground(new java.awt.Color(51, 51, 51));
        apellidosJLabel1.setText("Nombre:");

        nombreTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        nombreTF.setForeground(new java.awt.Color(153, 153, 153));
        nombreTF.setText("Introducir nombre");
        nombreTF.setMaximumSize(new java.awt.Dimension(80, 24));
        nombreTF.setMinimumSize(new java.awt.Dimension(80, 24));
        nombreTF.setPreferredSize(new java.awt.Dimension(160, 32));
        nombreTF.setSelectionColor(new java.awt.Color(204, 153, 255));
        nombreTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreTFMouseClicked(evt);
            }
        });
        nombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTFActionPerformed(evt);
            }
        });

        apellidosJLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        apellidosJLabel2.setForeground(new java.awt.Color(51, 51, 51));
        apellidosJLabel2.setText("Contraseña:");

        apellidosJLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        apellidosJLabel3.setForeground(new java.awt.Color(51, 51, 51));
        apellidosJLabel3.setText("Repetir contraseña:");

        jPasswordField2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.setMaximumSize(new java.awt.Dimension(80, 24));
        jPasswordField2.setMinimumSize(new java.awt.Dimension(80, 24));
        jPasswordField2.setPreferredSize(new java.awt.Dimension(80, 24));
        jPasswordField2.setSelectionColor(new java.awt.Color(204, 153, 255));
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setMaximumSize(new java.awt.Dimension(80, 24));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(80, 24));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(80, 24));
        jPasswordField1.setSelectionColor(new java.awt.Color(204, 153, 255));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apellidosJLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidosJLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidosJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidosJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BackjLabel1)
                            .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BackjLabel1)
                .addGap(18, 18, 18)
                .addComponent(apellidosJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apellidosJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apellidosJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apellidosJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackjLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackjLabel1MouseClicked
        this.setVisible(false);
        new MainView().setVisible(true);
    }//GEN-LAST:event_BackjLabel1MouseClicked

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        nombreTF.setText("");
        apellidosTF.setText("");
        emailTF.setText("");
        jPasswordField2.setText("");
        jPasswordField1.setText("");

    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed

        if (emailJLabel.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "No deje ningún campo vacío");
        } else {
            JOptionPane.showMessageDialog(null, "Formulario enviado con éxito.\n¡Bienvenid@ al Bar Giralda!");
        }

    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void nombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFActionPerformed

    private void nombreTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTFMouseClicked
        nombreTF.setText("");
    }//GEN-LAST:event_nombreTFMouseClicked

    private void apellidosTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidosTFMouseClicked
        apellidosTF.setText("");
    }//GEN-LAST:event_apellidosTFMouseClicked

    private void emailTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTFMouseClicked
        emailTF.setText("");
    }//GEN-LAST:event_emailTFMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        jPasswordField2.setText("");
    }//GEN-LAST:event_jPasswordField2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioRegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioRegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioRegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioRegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioRegistroView dialog = new FormularioRegistroView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackjLabel1;
    private javax.swing.JLabel apellidosJLabel;
    private javax.swing.JLabel apellidosJLabel1;
    private javax.swing.JLabel apellidosJLabel2;
    private javax.swing.JLabel apellidosJLabel3;
    private javax.swing.JTextField apellidosTF;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField nombreTF;
    // End of variables declaration//GEN-END:variables
}
