/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bargiralda.views.usuario;

import bargiralda.controllers.CrearFondo;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author zoom_
 */
public class UsuarioView extends javax.swing.JFrame {
    
    private static final String RUTA_FONDO_USUARIO = "/resources/backgroundModoUsuario.png";
    
    CrearFondo fondoUsuario = new CrearFondo(RUTA_FONDO_USUARIO);
    CrearFondo fondoAdmin = new CrearFondo(RUTA_FONDO_USUARIO);
    CrearFondo fondoPedido = new CrearFondo(RUTA_FONDO_USUARIO);
    /**
     * Creates new form BarView
     */
    public UsuarioView() {
        this.setContentPane(fondoUsuario);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAdminUser = new javax.swing.JDialog();
        jPanelAdminUser = new javax.swing.JPanel();
        BackjLabelAdmin = new javax.swing.JLabel();
        jButtonEditPass = new javax.swing.JButton();
        jPanelDatosPersonales = new javax.swing.JPanel();
        nombreJLabel = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        apellidosJLabel = new javax.swing.JLabel();
        apellidosTF = new javax.swing.JTextField();
        emailJLabel = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jPanelPassword = new javax.swing.JPanel();
        actualPassJLabel = new javax.swing.JLabel();
        jPasswordFieldAdminUser1 = new javax.swing.JPasswordField();
        nuevaPassJLabel = new javax.swing.JLabel();
        jPasswordFieldAdminUser2 = new javax.swing.JPasswordField();
        confirmarPassJLabel = new javax.swing.JLabel();
        jPasswordFieldAdminUser3 = new javax.swing.JPasswordField();
        cambiarPassJLabel = new javax.swing.JLabel();
        datosPersonalesJLabel = new javax.swing.JLabel();
        jButtonEditPersonal = new javax.swing.JButton();
        AdminUserTitleJLabel = new javax.swing.JLabel();
        jLabelAceptarDatosPersonales = new javax.swing.JLabel();
        jLabelCancelarDatosPersonales = new javax.swing.JLabel();
        jLabelAceptarPassword = new javax.swing.JLabel();
        jLabelCancelarPassword = new javax.swing.JLabel();
        jDialogVerPedido = new javax.swing.JDialog();
        jPanelEstadoPedido = new javax.swing.JPanel();
        abrirCajaLabel = new javax.swing.JLabel();
        BackjLabelCaja = new javax.swing.JLabel();
        jPanelDetallePedido = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaPuntuacion = new javax.swing.JTable();
        titleCartaJLabel = new javax.swing.JLabel();
        jPanelUsuario = new javax.swing.JPanel();
        adminUserLabel = new javax.swing.JLabel();
        verCartaLabel = new javax.swing.JLabel();
        hacerPedidoLabel = new javax.swing.JLabel();
        verEstadoLabel = new javax.swing.JLabel();
        BackjLabel = new javax.swing.JLabel();

        jDialogAdminUser.setContentPane(fondoAdmin);
        jDialogAdminUser.setTitle("Bar Giralda - Administrar cuenta");
        jDialogAdminUser.setMinimumSize(new java.awt.Dimension(1021, 1022));
        jDialogAdminUser.setSize(new java.awt.Dimension(1021, 1022));

        jPanelAdminUser.setLayout(new GridLayout(2, 2, 10, 10));
        jPanelAdminUser.setBackground(new Color(255, 255, 255, 220));
        jPanelAdminUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));

        BackjLabelAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BackLogo.png"))); // NOI18N
        BackjLabelAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackjLabelAdminMouseClicked(evt);
            }
        });

        jButtonEditPass.setBackground(new java.awt.Color(237, 28, 36));
        jButtonEditPass.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jButtonEditPass.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditPass.setText("Editar");
        jButtonEditPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButtonEditPass.setBorderPainted(false);
        jButtonEditPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditPass.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButtonEditPass.setMaximumSize(new java.awt.Dimension(230, 40));
        jButtonEditPass.setMinimumSize(new java.awt.Dimension(230, 40));
        jButtonEditPass.setPreferredSize(new java.awt.Dimension(230, 40));
        jButtonEditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPassActionPerformed(evt);
            }
        });

        jPanelDatosPersonales.setBackground(new Color(202, 240, 248, 110));
        jPanelDatosPersonales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jPanelDatosPersonales.setPreferredSize(new java.awt.Dimension(718, 230));

        nombreJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nombreJLabel.setForeground(new java.awt.Color(51, 51, 51));
        nombreJLabel.setText("Nombre:");

        nombreTF.setEditable(false);
        nombreTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        nombreTF.setForeground(new java.awt.Color(153, 153, 153));
        nombreTF.setText("Introducir nombre");
        nombreTF.setMaximumSize(new java.awt.Dimension(80, 24));
        nombreTF.setMinimumSize(new java.awt.Dimension(80, 24));
        nombreTF.setPreferredSize(new java.awt.Dimension(160, 32));
        nombreTF.setSelectionColor(new java.awt.Color(204, 153, 255));

        apellidosJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        apellidosJLabel.setForeground(new java.awt.Color(51, 51, 51));
        apellidosJLabel.setText("Apellidos:");

        apellidosTF.setEditable(false);
        apellidosTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        apellidosTF.setForeground(new java.awt.Color(153, 153, 153));
        apellidosTF.setText("Introducir apellidos");
        apellidosTF.setMaximumSize(new java.awt.Dimension(80, 24));
        apellidosTF.setMinimumSize(new java.awt.Dimension(80, 24));
        apellidosTF.setPreferredSize(new java.awt.Dimension(160, 32));
        apellidosTF.setSelectionColor(new java.awt.Color(204, 153, 255));

        emailJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        emailJLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailJLabel.setText("Correo electrónico:");

        emailTF.setEditable(false);
        emailTF.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        emailTF.setForeground(new java.awt.Color(153, 153, 153));
        emailTF.setText("Introducir email");
        emailTF.setMaximumSize(new java.awt.Dimension(80, 24));
        emailTF.setMinimumSize(new java.awt.Dimension(80, 24));
        emailTF.setPreferredSize(new java.awt.Dimension(160, 32));
        emailTF.setSelectionColor(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanelDatosPersonalesLayout = new javax.swing.GroupLayout(jPanelDatosPersonales);
        jPanelDatosPersonales.setLayout(jPanelDatosPersonalesLayout);
        jPanelDatosPersonalesLayout.setHorizontalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(162, 406, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelDatosPersonalesLayout.setVerticalGroup(
            jPanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apellidosJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPassword.setBackground(new Color(202, 240, 248, 110));
        jPanelPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));

        actualPassJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        actualPassJLabel.setForeground(new java.awt.Color(51, 51, 51));
        actualPassJLabel.setText("Contraseña actual:");

        jPasswordFieldAdminUser1.setEditable(false);
        jPasswordFieldAdminUser1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jPasswordFieldAdminUser1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldAdminUser1.setText("jPasswordField1");
        jPasswordFieldAdminUser1.setMaximumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser1.setMinimumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser1.setPreferredSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser1.setSelectionColor(new java.awt.Color(204, 153, 255));

        nuevaPassJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nuevaPassJLabel.setForeground(new java.awt.Color(51, 51, 51));
        nuevaPassJLabel.setText("Nueva contraseña:");

        jPasswordFieldAdminUser2.setEditable(false);
        jPasswordFieldAdminUser2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jPasswordFieldAdminUser2.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldAdminUser2.setText("jPasswordField1");
        jPasswordFieldAdminUser2.setMaximumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser2.setMinimumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser2.setPreferredSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser2.setSelectionColor(new java.awt.Color(204, 153, 255));

        confirmarPassJLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        confirmarPassJLabel.setForeground(new java.awt.Color(51, 51, 51));
        confirmarPassJLabel.setText("Confirmar nueva contraseña:");

        jPasswordFieldAdminUser3.setEditable(false);
        jPasswordFieldAdminUser3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jPasswordFieldAdminUser3.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldAdminUser3.setText("jPasswordField1");
        jPasswordFieldAdminUser3.setMaximumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser3.setMinimumSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser3.setPreferredSize(new java.awt.Dimension(80, 24));
        jPasswordFieldAdminUser3.setSelectionColor(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanelPasswordLayout = new javax.swing.GroupLayout(jPanelPassword);
        jPanelPassword.setLayout(jPanelPasswordLayout);
        jPanelPasswordLayout.setHorizontalGroup(
            jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(actualPassJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(jPasswordFieldAdminUser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelPasswordLayout.createSequentialGroup()
                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nuevaPassJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldAdminUser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldAdminUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmarPassJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelPasswordLayout.setVerticalGroup(
            jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualPassJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldAdminUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaPassJLabel)
                    .addComponent(confirmarPassJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldAdminUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldAdminUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );

        cambiarPassJLabel.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        cambiarPassJLabel.setForeground(new java.awt.Color(0, 204, 204));
        cambiarPassJLabel.setText("Cambiar contraseña");

        datosPersonalesJLabel.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        datosPersonalesJLabel.setForeground(new java.awt.Color(0, 204, 204));
        datosPersonalesJLabel.setText("Datos personales");

        jButtonEditPersonal.setBackground(new java.awt.Color(237, 28, 36));
        jButtonEditPersonal.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jButtonEditPersonal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditPersonal.setText("Editar");
        jButtonEditPersonal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButtonEditPersonal.setBorderPainted(false);
        jButtonEditPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditPersonal.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButtonEditPersonal.setMaximumSize(new java.awt.Dimension(230, 40));
        jButtonEditPersonal.setMinimumSize(new java.awt.Dimension(230, 40));
        jButtonEditPersonal.setPreferredSize(new java.awt.Dimension(230, 40));
        jButtonEditPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPersonalActionPerformed(evt);
            }
        });

        AdminUserTitleJLabel.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        AdminUserTitleJLabel.setForeground(new java.awt.Color(0, 204, 204));
        AdminUserTitleJLabel.setText("Administrar Usuario");

        jLabelAceptarDatosPersonales.setVisible(false);
        jLabelAceptarDatosPersonales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirmarBoton.png"))); // NOI18N
        jLabelAceptarDatosPersonales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAceptarDatosPersonalesMouseClicked(evt);
            }
        });

        jLabelCancelarDatosPersonales.setVisible(false);
        jLabelCancelarDatosPersonales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelarBoton.png"))); // NOI18N
        jLabelCancelarDatosPersonales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelarDatosPersonalesMouseClicked(evt);
            }
        });

        jLabelAceptarPassword.setVisible(false);
        jLabelAceptarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirmarBoton.png"))); // NOI18N
        jLabelAceptarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAceptarPasswordMouseClicked(evt);
            }
        });

        jLabelCancelarPassword.setVisible(false);
        jLabelCancelarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelarBoton.png"))); // NOI18N
        jLabelCancelarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelarPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminUserLayout = new javax.swing.GroupLayout(jPanelAdminUser);
        jPanelAdminUser.setLayout(jPanelAdminUserLayout);
        jPanelAdminUserLayout.setHorizontalGroup(
            jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                        .addComponent(jButtonEditPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelAceptarDatosPersonales)
                        .addGap(25, 25, 25)
                        .addComponent(jLabelCancelarDatosPersonales))
                    .addComponent(datosPersonalesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiarPassJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                        .addComponent(jButtonEditPass, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelAceptarPassword)
                        .addGap(25, 25, 25)
                        .addComponent(jLabelCancelarPassword))
                    .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                        .addComponent(BackjLabelAdmin)
                        .addGap(204, 204, 204)
                        .addComponent(AdminUserTitleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanelAdminUserLayout.setVerticalGroup(
            jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackjLabelAdmin)
                    .addComponent(AdminUserTitleJLabel))
                .addGap(32, 32, 32)
                .addComponent(datosPersonalesJLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminUserLayout.createSequentialGroup()
                        .addComponent(jButtonEditPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cambiarPassJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAceptarDatosPersonales)
                        .addComponent(jLabelCancelarDatosPersonales)))
                .addGap(18, 18, 18)
                .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAceptarPassword)
                        .addComponent(jLabelCancelarPassword)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAdminUserLayout = new javax.swing.GroupLayout(jDialogAdminUser.getContentPane());
        jDialogAdminUser.getContentPane().setLayout(jDialogAdminUserLayout);
        jDialogAdminUserLayout.setHorizontalGroup(
            jDialogAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAdminUserLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanelAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jDialogAdminUserLayout.setVerticalGroup(
            jDialogAdminUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAdminUserLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jPanelAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jDialogVerPedido.setContentPane(fondoPedido);
        jDialogVerPedido.setMinimumSize(new java.awt.Dimension(800, 800));
        jDialogVerPedido.setResizable(false);
        jDialogVerPedido.setSize(new java.awt.Dimension(800, 800));

        jPanelUsuario.setLayout(new GridLayout(2, 2, 10, 10));
        jPanelEstadoPedido.setBackground(new Color(255, 255, 255, 230));
        jPanelEstadoPedido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));

        abrirCajaLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        abrirCajaLabel.setForeground(new java.awt.Color(51, 51, 51));
        abrirCajaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/estadoPedidoEnCamino.png"))); // NOI18N

        BackjLabelCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BackLogo.png"))); // NOI18N
        BackjLabelCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackjLabelCajaMouseClicked(evt);
            }
        });

        jPanelDetallePedido.setBackground(new Color(255, 255, 255, 200));
        jPanelDetallePedido.setMaximumSize(new java.awt.Dimension(120, 150));
        jPanelDetallePedido.setMinimumSize(new java.awt.Dimension(120, 150));
        jPanelDetallePedido.setPreferredSize(new java.awt.Dimension(120, 150));

        tablaPuntuacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Coca-cola",  new Integer(2),  new Float(1.2),  new Float(2.4)},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Artículo", "Unidades", "Importe", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaPuntuacion);

        javax.swing.GroupLayout jPanelDetallePedidoLayout = new javax.swing.GroupLayout(jPanelDetallePedido);
        jPanelDetallePedido.setLayout(jPanelDetallePedidoLayout);
        jPanelDetallePedidoLayout.setHorizontalGroup(
            jPanelDetallePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetallePedidoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDetallePedidoLayout.setVerticalGroup(
            jPanelDetallePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetallePedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        titleCartaJLabel.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        titleCartaJLabel.setForeground(new java.awt.Color(0, 204, 204));
        titleCartaJLabel.setText("Estado de Pedido");

        javax.swing.GroupLayout jPanelEstadoPedidoLayout = new javax.swing.GroupLayout(jPanelEstadoPedido);
        jPanelEstadoPedido.setLayout(jPanelEstadoPedidoLayout);
        jPanelEstadoPedidoLayout.setHorizontalGroup(
            jPanelEstadoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoPedidoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelEstadoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEstadoPedidoLayout.createSequentialGroup()
                        .addComponent(BackjLabelCaja)
                        .addGap(60, 60, 60)
                        .addComponent(titleCartaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEstadoPedidoLayout.createSequentialGroup()
                        .addComponent(abrirCajaLabel)
                        .addGap(50, 50, 50)
                        .addComponent(jPanelDetallePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelEstadoPedidoLayout.setVerticalGroup(
            jPanelEstadoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoPedidoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelEstadoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackjLabelCaja)
                    .addComponent(titleCartaJLabel))
                .addGap(50, 50, 50)
                .addGroup(jPanelEstadoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abrirCajaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDetallePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogVerPedidoLayout = new javax.swing.GroupLayout(jDialogVerPedido.getContentPane());
        jDialogVerPedido.getContentPane().setLayout(jDialogVerPedidoLayout);
        jDialogVerPedidoLayout.setHorizontalGroup(
            jDialogVerPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerPedidoLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanelEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jDialogVerPedidoLayout.setVerticalGroup(
            jDialogVerPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerPedidoLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jPanelEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bar Giralda - Home (Modo Usuario)");
        setMinimumSize(new java.awt.Dimension(1021, 1022));
        setResizable(false);
        setSize(new java.awt.Dimension(1021, 1022));

        jPanelUsuario.setLayout(new GridLayout(2, 2, 10, 10));
        jPanelUsuario.setBackground(new Color(255, 255, 255, 200));
        jPanelUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));

        adminUserLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        adminUserLabel.setForeground(new java.awt.Color(51, 51, 51));
        adminUserLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/AdminCuentaLogo.png"))); // NOI18N
        adminUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminUserLabelMouseClicked(evt);
            }
        });

        verCartaLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        verCartaLabel.setForeground(new java.awt.Color(51, 51, 51));
        verCartaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/VerCartaLogo.png"))); // NOI18N
        verCartaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verCartaLabelMouseClicked(evt);
            }
        });

        hacerPedidoLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        hacerPedidoLabel.setForeground(new java.awt.Color(51, 51, 51));
        hacerPedidoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HacerPedidoLogo.png"))); // NOI18N
        hacerPedidoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hacerPedidoLabelMouseClicked(evt);
            }
        });

        verEstadoLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        verEstadoLabel.setForeground(new java.awt.Color(51, 51, 51));
        verEstadoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/VerEstadoPedidoLogo.png"))); // NOI18N
        verEstadoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verEstadoLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(verCartaLabel)
                .addGap(47, 47, 47)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hacerPedidoLabel)
                    .addComponent(adminUserLabel))
                .addGap(49, 49, 49)
                .addComponent(verEstadoLabel)
                .addGap(30, 30, 30))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verCartaLabel)
                    .addComponent(hacerPedidoLabel)
                    .addComponent(verEstadoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(adminUserLabel)
                .addGap(30, 30, 30))
        );

        BackjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BackLogo.png"))); // NOI18N
        BackjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackjLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackjLabel)
                    .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(BackjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackjLabelMouseClicked
        new UsuarioLoginView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackjLabelMouseClicked

    private void BackjLabelAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackjLabelAdminMouseClicked
        jDialogAdminUser.setVisible(false); 
    }//GEN-LAST:event_BackjLabelAdminMouseClicked

    private void jButtonEditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPassActionPerformed
        jPasswordFieldAdminUser1.setEditable(true);
        jPasswordFieldAdminUser2.setEditable(true);
        jPasswordFieldAdminUser3.setEditable(true);
        jLabelAceptarPassword.setVisible(true);
        jLabelCancelarPassword.setVisible(true);
      
    }//GEN-LAST:event_jButtonEditPassActionPerformed

    private void adminUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUserLabelMouseClicked
        jDialogAdminUser.setVisible(true);
    }//GEN-LAST:event_adminUserLabelMouseClicked

    private void jButtonEditPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPersonalActionPerformed
        nombreTF.setEditable(true);
        apellidosTF.setEditable(true);
        emailTF.setEditable(true);
        jLabelAceptarDatosPersonales.setVisible(true);
        jLabelCancelarDatosPersonales.setVisible(true);
    }//GEN-LAST:event_jButtonEditPersonalActionPerformed

    private void jLabelAceptarDatosPersonalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAceptarDatosPersonalesMouseClicked
        jLabelAceptarDatosPersonales.setVisible(false);
        jLabelCancelarDatosPersonales.setVisible(false);
        JOptionPane.showMessageDialog(null, "Cambios realizados con éxito");
    }//GEN-LAST:event_jLabelAceptarDatosPersonalesMouseClicked

    private void jLabelCancelarDatosPersonalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarDatosPersonalesMouseClicked
        jLabelAceptarDatosPersonales.setVisible(false);
        jLabelCancelarDatosPersonales.setVisible(false);
        JOptionPane.showMessageDialog(null, "No se ha realizado ningún cambio");
    }//GEN-LAST:event_jLabelCancelarDatosPersonalesMouseClicked

    private void jLabelAceptarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAceptarPasswordMouseClicked
        jLabelAceptarPassword.setVisible(false);
        jLabelCancelarPassword.setVisible(false);
        JOptionPane.showMessageDialog(null, "Cambios realizados con éxito");
    }//GEN-LAST:event_jLabelAceptarPasswordMouseClicked

    private void jLabelCancelarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelarPasswordMouseClicked
        jLabelAceptarPassword.setVisible(false);
        jLabelCancelarPassword.setVisible(false);
        JOptionPane.showMessageDialog(null, "No se ha realizado ningún cambio");
    }//GEN-LAST:event_jLabelCancelarPasswordMouseClicked

    private void verCartaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verCartaLabelMouseClicked
        new CartaView(this, true).setVisible(true);
    }//GEN-LAST:event_verCartaLabelMouseClicked

    private void BackjLabelCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackjLabelCajaMouseClicked
        this.setVisible(true);
    }//GEN-LAST:event_BackjLabelCajaMouseClicked

    private void verEstadoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verEstadoLabelMouseClicked
        jDialogVerPedido.setVisible(true);
    }//GEN-LAST:event_verEstadoLabelMouseClicked

    private void hacerPedidoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hacerPedidoLabelMouseClicked
        JOptionPane.showMessageDialog(this, "Funcionabilidad aún no desarrollada. Disculpen las molestías");
    }//GEN-LAST:event_hacerPedidoLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminUserTitleJLabel;
    private javax.swing.JLabel BackjLabel;
    private javax.swing.JLabel BackjLabelAdmin;
    private javax.swing.JLabel BackjLabelCaja;
    private javax.swing.JLabel abrirCajaLabel;
    private javax.swing.JLabel actualPassJLabel;
    private javax.swing.JLabel adminUserLabel;
    private javax.swing.JLabel apellidosJLabel;
    private javax.swing.JTextField apellidosTF;
    private javax.swing.JLabel cambiarPassJLabel;
    private javax.swing.JLabel confirmarPassJLabel;
    private javax.swing.JLabel datosPersonalesJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel hacerPedidoLabel;
    private javax.swing.JButton jButtonEditPass;
    private javax.swing.JButton jButtonEditPersonal;
    private javax.swing.JDialog jDialogAdminUser;
    private javax.swing.JDialog jDialogVerPedido;
    private javax.swing.JLabel jLabelAceptarDatosPersonales;
    private javax.swing.JLabel jLabelAceptarPassword;
    private javax.swing.JLabel jLabelCancelarDatosPersonales;
    private javax.swing.JLabel jLabelCancelarPassword;
    private javax.swing.JPanel jPanelAdminUser;
    private javax.swing.JPanel jPanelDatosPersonales;
    private javax.swing.JPanel jPanelDetallePedido;
    private javax.swing.JPanel jPanelEstadoPedido;
    private javax.swing.JPanel jPanelPassword;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JPasswordField jPasswordFieldAdminUser1;
    private javax.swing.JPasswordField jPasswordFieldAdminUser2;
    private javax.swing.JPasswordField jPasswordFieldAdminUser3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel nombreJLabel;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel nuevaPassJLabel;
    private javax.swing.JTable tablaPuntuacion;
    private javax.swing.JLabel titleCartaJLabel;
    private javax.swing.JLabel verCartaLabel;
    private javax.swing.JLabel verEstadoLabel;
    // End of variables declaration//GEN-END:variables
}
